apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: react-app=iko16/react-app
    argocd-image-updater.argoproj.io/react-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/react-app.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/iko16-haekal/learn-argocd
    targetRevision: main
    path: nginx-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
